from enum import Enum

Eps = Enum('Eps', 'ASMETSALUD SURA MEDIMAS')

Rh = Enum('Rh', 'O_POSITIVE O_NEGATIVE A_POSITIVE A_NEGATIVE B_POSITIVE B_NEGATIVE AB_POSITIVE AB_NEGATIVE UNSPECIFIED')

Gender = Enum('Gender', 'MALE FEMALE NO-BINARY')

Purpose = Enum('Purpose', 'REDUCE TONE_UP DEVELOP PHYSICAL_THERAPY CONDITIONING')

Type = Enum('')